execute as @e[type=armor_stand,tag=PhoenixParts,tag=Body] run data merge entity @s {Pose:{Head:[0f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Neck] run data merge entity @s {Pose:{Head:[30f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Head] run data merge entity @s {Pose:{Head:[20f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL0] run data merge entity @s {Pose:{Head:[10f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL1] run data merge entity @s {Pose:{Head:[-30f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL2] run data merge entity @s {Pose:{Head:[0f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR0] run data merge entity @s {Pose:{Head:[10f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR1] run data merge entity @s {Pose:{Head:[-30f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR2] run data merge entity @s {Pose:{Head:[0f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingL0] run data merge entity @s {Pose:{Head:[-20f,0f,20f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingL1] run data merge entity @s {Pose:{Head:[-20f,20f,-20f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingR0] run data merge entity @s {Pose:{Head:[-20f,0f,-20f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingR1] run data merge entity @s {Pose:{Head:[-20f,-20f,20f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Tail0] run data merge entity @s {Pose:{Head:[-40f,0f,0f]}}
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Tail1] run data merge entity @s {Pose:{Head:[-60f,0f,0f]}}
