scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Body] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 666
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Neck] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 666
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Head] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL0] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL1] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegL2] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR0] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR1] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=LegR2] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 2666
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingL0] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 2666
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingL1] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix -2667
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingR0] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix -2667
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=WingR1] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Tail0] run function #asa_matrix:animate_setparam
scoreboard players set #asa_animate_x AsaMatrix 0
scoreboard players set #asa_animate_y AsaMatrix 0
scoreboard players set #asa_animate_z AsaMatrix 0
execute as @e[type=armor_stand,tag=PhoenixParts,tag=Tail1] run function #asa_matrix:animate_setparam
